version: "3.8"
services:
  frontend:
    build: ./frontend
    ports: 
    - 3000:3000
    stdin_open: true
    volumes: 
    - ./frontend:/reactApp
    - /reactApp/node_modules
    depends_on: 
      - backend
  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root